### PR TITLE
 New plugin: FilteredForumSearch

### PR DESCRIPTION
**Pull request by TwistedTwigleg**
This PR adds a new plugin for searching using additional filters in Vanilla without any additional software beyond the plugin itself.

The plugin allows for searching by:
* Category
* Q&A status
* Post Count
* Username

Probably overkill for what we need, but it was fun and I learned a lot about SQL.

_______

The plugin is a heavily modified version of another Vanilla plugin called CategorySearch. Most of the code has been rewritten or replaced entirely, with just a few places still maintaining the original plugin code. At some point I'll need to go through and rewrite/rework the rest, but everything works as far as I can tell.

This plugin uses SQL with additional parameters to perform the filtered search. While perhaps not optimal for large databases that get hundreds/thousands of searches, for the Godot forums it should be okay. I suppose worse case, the server provider complains, we disable the plugin, and go back to using the default Vanilla search.

The plugin relies heavily on the interface Vanilla provides for calling SQL and uses no direct queries. This should, assuming Vanilla's interface is setup correctly, make most/all SQL injection attacks impossible to perform. I did some tests on my local machine and couldn't inject any SQL code.

_______

I tested on a localhost instance of the server and everything seems to work fine there. I think it should work on the live server as well without any additional edits since it doesn't have any dependencies beyond Vanilla, SQL, and the Q&A plugin.

@Megalomaniak - Do you mind looking over the plugin if you have a chance? I think everything should work, but given it uses the SQL database where all of the forum data is stored, another pair of eyes looking over it would probably be a good idea.

### CODE REVIEW

**Comment by Megalomaniak** [comment]
Honestly I'm no PHP guru myself, so the best way to get good feedback might be to release it on the vanilla plugins platform, and maybe get some feedback from the https://open.vanillaforums.com/ forums. I bet theres plenty of developers/users there who would be intrigued and interested. And with a lot more experience in PHP.

In as far as I can tell, looks good and if it works, it works. Whether it can be more optimal in terms of say performance, I don't really know.

**Comment by TwistedTwigleg** [comment]
Good idea! I’ll make a post on the Vanilla forums and see what they think.

I also don’t really have a lot of PHP experience, just what I have picked up here and there, which is why I didn’t want to just upload the plugin to the live forum without anyone looking at it, in case I made some stupid mistake.

Thanks for looking over it!

Do you think we should put the plugin on the live forum, or wait to see what the Vanilla forums developers/users have had a chance to look at it?

**Comment by Megalomaniak** [comment]
I'd say up to you, but I think its relatively safe to deploy it and make a topic in forum chat letting users know about the new search and asking for user's feedback on it.

**Comment by TwistedTwigleg** [comment]
Okay, if you think it is safe to deploy, then I am all for it. I was just hesitant because of the potential, albeit probably small potential, for SQL injections. I'm going to merge this in, fix the defaults for the Discord plugin, and then deploy the updated plugins to the live forum.

**Pull request merged**
